twiword/collect_words/urls.py
from django.urls import path
from . import views
app_name = 'collect'
#1の人しか入れないよおおおおお
urlpatterns = [
    path('<int:userurl>/', views.userhome, name='userhome'),
    path('<int:userurl>/quiz', views.quiz, name='quiz'),
    path('<int:userurl>/list', views.wordlist, name='list'),
    path('<int:userurl>/result', views.result, name='result'),
    path('<int:userurl>/extract', views.extract, name='extract'),
    path('top/', views.top_page, name='top'),
]

twiword/twiword/urls.py
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),
    path('collect_words/', include('collect_words.urls', namespace='collect')),
    path('user/', include('user_auth.urls')),
    path('user/', include('social_django.urls', namespace='social')),
]

twiword/user_auth/urls.py
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from . import views
app_name='user_auth'

urlpatterns=[
    path('login/',
            LoginView.as_view(template_name='user_auth/login.html'),
            name='login'),
    path('logout/',
            LogoutView.as_view(template_name='user_auth/logout.html'),
            name='logout'),
    path('index/', views.index, name='index'),
]

twiword/collect_words/models.py
from django.db import models

class Words(models.Model):
    NAME = 5
    VERB = 10

    user = models.ForeignKey('Users', on_delete=models.CASCADE)
    tweet = models.CharField(max_length=200)
    word = models.CharField(max_length=200)
    trans = models.CharField(max_length=200)
    category = models.IntegerField(default=0)
    quiz = models.BooleanField(default=True)
    owner = models.CharField(max_length=200)

class Users(models.Model):
    screenName = models.CharField(max_length=50)
    userId = models.CharField(max_length=100)
    lastTweet = models.CharField(max_length=100, default='')
    imgUrl = models.CharField(max_length=100, default='')

twiword/collect_words/forms.py
from django import forms
from .models import Words

class QuizForm(forms.Form):
    class Meta:
        model = Words
        fields = ("user",
                  "tweet",
                  "word",
                  "trans",
                  "category",
                  "quiz",
                  "owner")

twiword/collect_words/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .sepjap import sep
from .models import Words
from .models import Users
from .forms import QuizForm
from django.contrib.auth.decorators import login_required
from social_django.models import UserSocialAuth
from .collect import collect, userImg
from .lanproc import language
import urllib.request
import urllib.parse
import xml.etree.ElementTree as ET

#indexは移動するかもしれません
@login_required
def top_page(request):
    user = UserSocialAuth.objects.get(user_id=request.user.id)
    userurl = user.access_token['user_id']
    #return render(request,'user_auth/top.html', {'user': user})
    context = {
        'user':user,
        'userurl': userurl,
    }
    return render(request,'user_auth/top.html', context)

def catch(request):
    texts='私はよく柿食う客だよ。'
    analyze = sep(texts)
    results = []
    for k, v in analyze:
        results.append(k)
    context = {
        'results': results[1],
    }
    print(results)
    return render(request, 'collect_words/catch.html',context)

@login_required
def userhome(request, userurl):
    user = UserSocialAuth.objects.get(user_id=request.user.id)
    if permittion(user, userurl):
        register = Users.objects.filter(userId=user.access_token['user_id'])
        if not register:
            imgUrl = userImg(user.access_token['screen_name'])
            newUser = Users.objects.create(screenName=user.access_token['screen_name'],
                                   userId=user.access_token['user_id'],
                                   imgUrl=imgUrl, 
                                   )
        register = Users.objects.get(userId=user.access_token['user_id'])
        words = Words.objects.filter(owner=user.access_token['user_id'])
        numberOfWords = words.count()
        numberOfCompleted = words.filter(quiz=False).count()
        if numberOfWords:
            percentageOfProgress = round(numberOfCompleted / numberOfWords * 100, 2)
        else:
            percentageOfProgress = 'N/A'
        context = {
            'words': words,
            'userurl': userurl,
            'user': user,
            'register': register,
            'numberOfWords': numberOfWords,
            'percentageOfProgress': percentageOfProgress,
            
        }
        return render(request, 'collect_words/userhome.html', context)
    else:
        return errorlog()

@login_required
def quiz(request, userurl):
    user = UserSocialAuth.objects.get(user_id=request.user.id)
    if permittion(user, userurl):
        if request.method == "POST":
            wordId = request.POST.get("wordId", "")
            word = Words.objects.get(id=int(wordId))
            word.quiz = False
            word.save()
            #word = Words.objects.filter(owner=user.access_token['user_id'],quiz=True).order_by("?").first()
            word = Words.objects.filter(owner=userurl, quiz=True).order_by("?").first()
            context = {
                'word': word,
                'userurl': userurl,
            }
            return render(request, 'collect_words/quiz.html', context)
        if request.method == "GET":
            #word = Words.objects.filter(owner=user.access_token['user_id'], quiz=True).order_by("?").first()
            word = Words.objects.filter(owner=userurl, quiz=True).order_by("?").first()
            context = {
                'word': word,
                'userurl': userurl,
            }
            return render(request, 'collect_words/quiz.html', context)
    else:
        return errorlog()

@login_required
def wordlist(request, userurl):
    user = UserSocialAuth.objects.get(user_id=request.user.id)
    if permittion(user, userurl):
        if request.method == "POST":
            wordId = request.POST.get("wordId", "")
            if request.POST.get("delete") == "True":
                    word = Words.objects.get(id=int(wordId))
                    word.delete()
                    words = Words.objects.filter(owner=userurl)
                    context = {
                        'words': words,
                        'userurl': userurl,
                        'user': user,
                    }
                    return render(request, 'collect_words/list.html', context)
            else:
                word = Words.objects.get(id=int(wordId))
                word.quiz = not(word.quiz)
                word.save()
                #words = Words.objects.filter(owner=user.access_token['user_id'])
                words = Words.objects.filter(owner=userurl)
                context = {
                    'words': words,
                    'userurl': userurl,
                    'user': user,
                }
                return render(request, 'collect_words/list.html', context)
        if request.method == "GET":
            #words = Words.objects.filter(owner=user.access_token['user_id'])
            words = Words.objects.filter(owner=userurl)
            context = {
                'words': words,
                'userurl': userurl,
                'user': user,
            }
            return render(request, 'collect_words/list.html', context)
    else:
        return errorlog()

@login_required
def result(request, userurl):
    user = UserSocialAuth.objects.get(user_id=request.user.id)
    if permittion(user, userurl):
        words = Words.objects.all()
        newlist = []
        screenName = user.access_token['screen_name']
        results = collect(screenName, newlist)
        context = {
            'words': words,
            'userurl': userurl,
            'results': results,
        }
        return render(request, 'collect_words/result.html', context)
    else:
        return errorlog()

@login_required
def extract(request, userurl):
    user = UserSocialAuth.objects.get(user_id=request.user.id)
    if permittion(user, userurl):
        if request.method == "POST":
            if request.POST.get("add")=="True":
                separated_word = request.POST.get("separated_word")
                query = {
                    'Dic':'EJdict',
                    'Word':separated_word,
                    'Scope':'HEADWORD',
                    'Match':'STARTWITH',
                    'Merge':'AND',
                    'Prof':'XHTML',
                    'PageSize':'1',
                    'PageIndex':'0',
                }
                p = urllib.parse.urlencode(query)
                url = 'http://public.dejizo.jp/NetDicV09.asmx/SearchDicItemLite?' + p
                req = urllib.request.Request(url)
                with urllib.request.urlopen(req) as response:
                    xml_string = response.read()
                root = ET.fromstring(xml_string)
                print(root[1].text)
                if int(root[1].text) == 0:
                    return HttpResponse("No word found")
                else:
                    dictId = root[3][0][0].text
                    params = {
                        'Dic':'EJdict',
                        'Item':dictId,
                        'Prof':'XHTML',
                        'Loc':'',
                    }
                    p = urllib.parse.urlencode(params)
                    url = 'http://public.dejizo.jp/NetDicV09.asmx/GetDicItemLite?' + p
                    req = urllib.request.Request(url)
                    with urllib.request.urlopen(req) as response:
                        xml_string = response.read()
                    root = ET.fromstring(xml_string)
                    trans = root[2][0][0].text
                    text = request.POST.get("text")
                    user = Users.objects.get(id=request.user.id)
                    Words.objects.create(user=user,
                                        tweet=text,
                                        word=separated_word,
                                        trans=trans,
                                        owner=userurl,
                                        )
                    name = request.POST.get("name")
                    profile_image_url = request.POST.get("profile_image_url", "")
                    separated_words = language(text)
                    for i in range(len(separated_words)):
                        if Words.objects.filter(word=separated_words[i]).exists():
                            separated_words[i] = "."
                    context = {
                        'name': name,
                        'profile_image_url': profile_image_url,
                        'text': text,
                        'separated_words': separated_words,
                        'userurl': userurl,
                    }
                    return render(request, 'collect_words/extract.html', context)
            else:
                name = request.POST.get("name")
                profile_image_url = request.POST.get("profile_image_url", "")
                text = request.POST.get("text", "")
                separated_words = language(text)
                for i in range(len(separated_words)):
                    if Words.objects.filter(word=separated_words[i]).exists():
                        separated_words[i] = "."
                context = {
                    'name': name,
                    'profile_image_url': profile_image_url,
                    'text': text,
                    'separated_words': separated_words,
                    'userurl': userurl,
                }
                return render(request, 'collect_words/extract.html', context)
        else:
            return errorlog()
    else:
        return errorlog()

def permittion(user, userurl):
    if not user.access_token["user_id"] == str(userurl):
        return False
    else:
        return True

def errorlog():
    return HttpResponse("ERROR")

def translate(word):
    url = 'http://public.dejizo.jp/NetDicV09.asmx/SearchDicItemLite'
    query = {
        'Dic':'EJdict',
        'Word':'infinity',
        'Scope':'HEADWORD',
        'Match':'STARTWITH',

twiword/collect_words/templates/collect_words/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>TwiWord</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'collect_words/css/style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    </head>
    <body>
        <header>
                <nav class="navbar navbar-expand navbar-light bg-light">
                        <a class="navbar-brand" href="{% url 'collect:userhome' userurl %}"><img src="{% static "collect_words/sources/logo/1_Primary_logo_on_transparent_295x65.png" %}" alt=""></a>
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item"><a class="nav-link" href="{% url 'collect:userhome' userurl %}">HOME</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'collect:quiz' userurl %}">Quiz</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'collect:list' userurl %}">Word List</a></li>
                            <li class="nav-item"><a class="nav-link" href="/user/logout">SignOut</a></li>
                        </ul>
                </nav>           
        </header>
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <footer class="bd-footer text-muted bg-light">
                <div class="container">
                    <h5>Links</h5>
                    <ul class="bd-footer-links list-unstyled">
                        <li><a href="{% url 'collect:userhome' userurl %}">HOME</a></li>
                        <li><a href="{% url 'collect:quiz' userurl %}">Quiz</a></li>
                        <li><a href="{% url 'collect:list' userurl %}">Word List</a></li>
                        <li><a href="{% url 'user_auth:index' %}">SignOut</a></li>
                    </ul>
                    <small>&copy; 2019 TwiWord.</small>
                </div>
            </footer>
    </body>
</html>

twiword/collect_words/templates/collect_words/extract.html
{% extends 'collect_words/base.html' %}
    {% block content %}
    <div id="main" class="my-3">
        <h1>Extract completed</h1>
        <div>
            <div>
                <img src={{ profile_image_url }} alt="twitterimg">
            </div>
            <h3>{{ name }}</h3>
            <p>{{ text }}</p>
        </div>
        <hr>
        <div id="extract">
            {% for separated_word in separated_words %}
                {% if separated_word|length  > 1 %}
                    <form method="post" action="{% url 'collect:extract' userurl%}">
                            {% csrf_token %}
                            <input type="hidden" name="text" value="{{ text }}">
                            <input type="hidden" name="name" value="{{ name }}">
                            <input type="hidden" name="profile_image_url" value="{{ profile_image_url }}">
                            <input type="hidden" name="separated_word" value="{{ separated_word }}">
                            <input type="hidden" name="add" value="True">
                            <button class='btn btn-primary my-1' type="submit" >{{ separated_word }}</button>
                    </form>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

twiword/collect_words/templates/collect_words/index.html
{% extends 'collect_words/base.html' %}
    {% block content %}
    {% load static %}
            <div id="main">
                <article>
                    <div id="main_visu">
                        <p><img src="{% static "collect_words/sources/logo/main_visu.png" %}" alt="mainvis"></p>
                    </div>
                    <div id="How to Use">
                        <h1>How to Use</h1>
                        <h2>Follow twitter</h2>
                        <h2>Sign in this app</h2>
                        <h2>collect words from your tweets</h2>
                        <h2>solving quiz!</h2>
                        <a class="btn btn-info" href="{% url 'collect:userhome' userurl %}">Get Start</a>
                    </div>
                </article>
            </div>
    {% endblock %}

twiword/collect_words/templates/collect_words/list.html
{% extends 'collect_words/base.html' %}
    {% block content %}
            <div id="main" class="my-3">
                    <input class="btn btn-info" type="button" value="Sort">
                <p>↑更新順、アルファベット順ってなったらいいね</p>
                <article id="wordlist">
                        <table align="center">
                                <tr>
                                    <th>英語</th>
                                    <th>日本語</th>
                                    <th>品詞</th>
                                    <th>出題</th>
                                </tr>
                                {% if words %}
                                    {% for word in words %}
                                            <tr>
                                            <td>{{ word.word }}</td>
                                            <td>{{ word.trans }}</td>
                                            {% if word.quiz == False %}
                                                <td>
                                                    <form method="post" action="{% url 'collect:list' userurl%}">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="wordId" value="{{ word.id }}">
                                                        <button class='btn btn-primary my-3' type="submit" >Quizに登録</button>
                                                    </form>
                                                </td>
                                            {% else %}
                                                <td>
                                                    <form method="post" action="{% url 'collect:list' userurl%}">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="wordId" value="{{ word.id }}">
                                                        <button class='btn btn-warning my-3' type="submit" >Quizから消す</button>
                                                    </form>
                                                </td>
                                            {% endif %}
                                            <td>
                                                    <form method="post" action="{% url 'collect:list' userurl%}">
                                                        {% csrf_token %}
                                                        <input type="hidden" name="delete" value="True">
                                                        <input type="hidden" name="wordId" value="{{ word.id }}">
                                                        <button class='btn btn-danger my-3' type="submit" >削除</button>
                                                    </form>
                                                </td>
                                            </tr>
                                            
                                    {% endfor %}
                                {% else %}
                                    <p>No words available</p>
                                {% endif %}
                        </table>
                </article>
            </div>
    {% endblock %}
        

twiword/collect_words/templates/collect_words/quiz.html
{% extends 'collect_words/base.html' %}
    {% block content %}
        <div id="main">
            <article>
                <h1>Quiz</h1>
                {% if word %}
                            <h2>{{ word.word }}</h2>
                {% else %}
                    <p>No words available</p>
                {% endif %}
                <br>
                <input class="btn btn-info" type="button" value="Answer">
                <div id="answer">
                    <p>{{ word.trans }}</p>
                    <h4>元のツイート:</h4>
                    <p>{{ word.tweet }}</p>   
                    <div>
                        {% if word.id %}
                            <form method="post" action="{% url 'collect:quiz' userurl%}">
                                {% csrf_token %}
                                <input type="hidden" name="wordId" value={{ word.id }}>
                                <button class='btn btn-info my-3' type="submit" >覚えた</button>
                            </form>
                            <a class='btn btn-info my-3' href="{% url 'collect:quiz' userurl%}">まだ</a> 
                        {% endif %} 
                    </div>               
                </div>
            </article>
        </div>
    {% endblock %}
        

twiword/collect_words/templates/collect_words/result.html
{% extends 'collect_words/base.html' %}
    {% block content %}
    <div id="main" class="my-3">
        <h1>New Tweet List</h1>
        <div id="tweetList">
            {% for result in results %}
                <div class="card border-primary mb-3">
                    <div>
                        <img src={{ result.profile_image_url }} alt="twitterimg">
                    </div>
                    <h3>{{ result.name }}</h3>
                    <p>@{{ result.screen_name }}</p>
                    <p>{{ result.text }}</p>
                    <form method="post" action="{% url 'collect:extract' userurl%}">
                        {% csrf_token %}
                        <input type="hidden" name="text" value="{{ result.text }}">
                        <input type="hidden" name="name" value="{{ result.name }}">
                        <input type="hidden" name="profile_image_url" value="{{ result.profile_image_url }}">
                        <input type="hidden" name="add" value="False">
                        <button class='btn btn-info my-3' type="submit" >解析</button>
                    </form>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

twiword/collect_words/templates/collect_words/userhome.html
{% extends 'collect_words/base.html' %}
    {% block content %}
    {% load static %}
                    <div id="col">
                        <div id="main_visu">
                        </div>
                        <p id="col"><strong>You can add new vocaburaries from Twitter!</strong></p>
                        <a class="btn btn-info" href="{% url 'collect:result' userurl %}">Collect from Twitter!</a>
                    </div>
                    <hr>
                    <div>
                            <div class="col-3 float-left my-3 ">
                                <aside>
                                    <img id="profimg" src={{ register.imgUrl }} alt="twitterimg">
                                        <h3>ようこそ@{{ user.access_token.screen_name }}さん</h3>

                                </aside>
                            </div>
                            <div class="col-9 float-left my-3">
                                <h3>Contributions</h3>
                                <h3>Now you have {{ numberOfWords }} words</h3>
                                <h3>Persectage of your achievement</h3>
                                <h3>{{ percentageOfProgress }} %</h3>
                            </div>
                        </div>    
       {% endblock %}